export type Product = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  image: string;
  shortDescription: string;
  description: string;
  origin: string;
  features: string[];
  specifications: Record<string, string>;
};

export const categories = [
  { name: "All", slug: "all" },
  { name: "Whole Spices", slug: "whole-spices" },
  { name: "Ground Spices", slug: "ground-spices" },
  { name: "Dehydrated Vegetables", slug: "dehydrated" },
  { name: "Seeds & Grains", slug: "seeds-grains" },
  { name: "Oils", slug: "oils" },
] as const;

export const products: Product[] = [
  {
    slug: "garlic-powder",
    name: "Garlic Powder",
    category: "Ground Spices",
    categorySlug: "ground-spices",
    image: "/images/products/garlic-powder.jpg",
    shortDescription: "Premium dehydrated garlic powder with rich aroma and flavor, perfect for food processing and seasoning blends.",
    description: "Our premium garlic powder is sourced from the finest garlic bulbs, carefully dehydrated and ground to a fine consistency. It retains the natural oils and flavors that make Indian garlic renowned worldwide. Ideal for food manufacturers, seasoning blenders, and wholesale distributors.",
    origin: "India",
    features: [
      "100% pure dehydrated garlic",
      "Fine mesh size: 80-100 mesh",
      "Moisture content: < 6%",
      "Strong natural aroma and flavor",
      "No additives or preservatives",
      "Shelf life: 12 months",
      "Available in 25kg and 50kg packaging",
    ],
    specifications: {
      "Product": "Garlic Powder",
      "Origin": "India (Gujarat, Madhya Pradesh)",
      "Mesh Size": "80-100 mesh",
      "Moisture": "< 6%",
      "Color": "Off-white to cream",
      "Packaging": "25kg / 50kg PP bags, cartons",
      "MOQ": "1 MT",
      "Shelf Life": "12 months",
      "Certifications": "FSSAI, ISO 22000, HACCP",
    },
  },
  {
    slug: "turmeric-powder",
    name: "Turmeric Powder",
    category: "Ground Spices",
    categorySlug: "ground-spices",
    image: "/images/products/turmeric-powder.jpg",
    shortDescription: "High-curcumin turmeric powder from Erode and Salem regions, known for exceptional color and potency.",
    description: "Our turmeric powder is sourced from the renowned Erode and Salem regions of Tamil Nadu, India — known globally for producing the highest quality turmeric. With curcumin content ranging from 3-5%, our turmeric delivers exceptional color, flavor, and health benefits.",
    origin: "India",
    features: [
      "High curcumin content: 3-5%",
      "Vibrant golden-yellow color",
      "Fine particle size for uniform blending",
      "Steam-sterilized for food safety",
      "Non-irradiated processing available",
      "Shelf life: 18 months",
      "Custom packaging available",
    ],
    specifications: {
      "Product": "Turmeric Powder",
      "Origin": "India (Erode, Salem)",
      "Curcumin Content": "3-5%",
      "Moisture": "< 10%",
      "Color Value": "5-7% (ASTA method)",
      "Mesh Size": "60-80 mesh",
      "Packaging": "25kg PP bags, 50kg jute bags",
      "MOQ": "1 MT",
      "Shelf Life": "18 months",
      "Certifications": "FSSAI, APEDA, Spice Board",
    },
  },
  {
    slug: "red-chilli-powder",
    name: "Red Chilli Powder",
    category: "Ground Spices",
    categorySlug: "ground-spices",
    image: "/images/products/red-chilli.jpg",
    shortDescription: "Premium red chilli powder available in various heat levels, from mild Kashmiri to fiery Guntur varieties.",
    description: "We offer a wide range of red chilli powders sourced from India's premier chilli-growing regions. From the mild, color-rich Kashmiri chilli to the intensely hot Guntur and Byadgi varieties, our range caters to every heat preference and culinary application.",
    origin: "India",
    features: [
      "Multiple heat levels: mild to extra hot",
      "Rich natural red color",
      "ASTA color values: 80-180",
      "SHU range: 15,000-100,000",
      "Clean, consistent particle size",
      "Available in multiple mesh sizes",
      "Custom blends on request",
    ],
    specifications: {
      "Product": "Red Chilli Powder",
      "Origin": "India (Guntur, Byadgi, Kashmir)",
      "Heat Level": "15,000-100,000 SHU",
      "ASTA Color": "80-180",
      "Moisture": "< 10%",
      "Mesh Size": "40-80 mesh",
      "Packaging": "25kg laminated bags",
      "MOQ": "1 MT",
      "Shelf Life": "12 months",
      "Certifications": "FSSAI, ISO 22000",
    },
  },
  {
    slug: "black-pepper",
    name: "Black Pepper",
    category: "Whole Spices",
    categorySlug: "whole-spices",
    image: "/images/products/black-pepper.jpg",
    shortDescription: "Premium Malabar black pepper known as the 'King of Spices', with bold flavor and high piperine content.",
    description: "Our black pepper is sourced from the lush plantations of Kerala and Karnataka — the heartland of Indian pepper production. Malabar and Tellicherry grades are prized globally for their bold, complex flavor profile and high essential oil content.",
    origin: "India",
    features: [
      "Malabar & Tellicherry grades available",
      "High piperine content: 4-6%",
      "Bold, aromatic flavor profile",
      "Moisture: < 12%",
      "Clean and uniform berry size",
      "Machine-cleaned and sorted",
      "Bulk and retail packaging",
    ],
    specifications: {
      "Product": "Black Pepper (Whole)",
      "Origin": "India (Kerala, Karnataka)",
      "Grade": "Malabar / Tellicherry",
      "Piperine": "4-6%",
      "Moisture": "< 12%",
      "Berry Size": "4.75mm (550 g/L)",
      "Packaging": "25kg / 50kg jute / PP bags",
      "MOQ": "1 MT",
      "Shelf Life": "24 months",
      "Certifications": "FSSAI, Spice Board, APEDA",
    },
  },
  {
    slug: "cardamom",
    name: "Green Cardamom",
    category: "Whole Spices",
    categorySlug: "whole-spices",
    image: "/images/products/cardamom.jpg",
    shortDescription: "Aromatic green cardamom pods from the spice gardens of Kerala, ideal for culinary and beverage applications.",
    description: "Known as the 'Queen of Spices', our green cardamom is hand-picked from the misty hills of Kerala and Tamil Nadu. Each pod is carefully dried to preserve its intense, complex aroma — a blend of sweet, floral, and minty notes prized in cuisines worldwide.",
    origin: "India",
    features: [
      "Hand-picked and sun-dried",
      "Bold green color with intense aroma",
      "Grades: 8mm+, 7mm+, 6mm+",
      "Rich essential oil content",
      "Triple-cleaned and graded",
      "Premium and commercial grades",
      "Vacuum-sealed packaging available",
    ],
    specifications: {
      "Product": "Green Cardamom",
      "Origin": "India (Kerala, Tamil Nadu)",
      "Grade": "8mm Bold / 7mm / 6mm",
      "Moisture": "< 10%",
      "Essential Oil": "3-5%",
      "Color": "Natural green",
      "Packaging": "5kg / 10kg / 25kg cartons",
      "MOQ": "500 kg",
      "Shelf Life": "18 months",
      "Certifications": "FSSAI, Spice Board",
    },
  },
  {
    slug: "cumin-seeds",
    name: "Cumin Seeds",
    category: "Seeds & Grains",
    categorySlug: "seeds-grains",
    image: "/images/products/cumin-seeds.jpg",
    shortDescription: "High-quality cumin seeds from Gujarat and Rajasthan with rich essential oil content and earthy aroma.",
    description: "India is the world's largest producer and exporter of cumin, and our seeds come from the finest farms of Gujarat and Rajasthan. Our cumin is known for its strong, distinctive aroma, warm flavor, and high essential oil content.",
    origin: "India",
    features: [
      "Singapore/Europe quality standards",
      "High volatile oil content: 2.5-4%",
      "Clean and uniform seed size",
      "Machine-cleaned, 99%+ purity",
      "Available: whole seeds & powder",
      "Color-sorted for consistency",
      "Custom processing available",
    ],
    specifications: {
      "Product": "Cumin Seeds",
      "Origin": "India (Gujarat, Rajasthan)",
      "Purity": "99%+",
      "Volatile Oil": "2.5-4%",
      "Moisture": "< 10%",
      "Color": "Greenish-brown",
      "Packaging": "25kg / 50kg PP bags",
      "MOQ": "1 MT",
      "Shelf Life": "18 months",
      "Certifications": "FSSAI, APEDA, ISO 22000",
    },
  },
  {
    slug: "coriander-seeds",
    name: "Coriander Seeds",
    category: "Seeds & Grains",
    categorySlug: "seeds-grains",
    image: "/images/products/coriander.jpg",
    shortDescription: "Premium coriander seeds known for their citrusy aroma and warm flavor, available in whole and split form.",
    description: "Our coriander seeds are sourced from the top-producing regions of Rajasthan, Gujarat, and Madhya Pradesh. Known for their bright, citrusy aroma and warm flavor, they are essential in spice blends, curry powders, and food manufacturing worldwide.",
    origin: "India",
    features: [
      "Eagle and Scooter quality grades",
      "Bright citrusy aroma",
      "Available: whole, split, and powder",
      "Volatile oil content: 0.3-0.5%",
      "Uniform golden-brown color",
      "99%+ purity, machine-cleaned",
      "Available in bulk and retail packs",
    ],
    specifications: {
      "Product": "Coriander Seeds",
      "Origin": "India (Rajasthan, Gujarat, MP)",
      "Grade": "Eagle / Scooter",
      "Volatile Oil": "0.3-0.5%",
      "Moisture": "< 10%",
      "Purity": "99%+",
      "Packaging": "25kg / 50kg PP bags",
      "MOQ": "1 MT",
      "Shelf Life": "18 months",
      "Certifications": "FSSAI, APEDA",
    },
  },
  {
    slug: "dehydrated-onion",
    name: "Dehydrated Onion",
    category: "Dehydrated Vegetables",
    categorySlug: "dehydrated",
    image: "/images/products/dehydrated-onion.jpg",
    shortDescription: "Premium dehydrated onion in flakes, minced, and powder forms for food processing and seasoning industries.",
    description: "Our dehydrated onion products are made from fresh, premium-quality Indian onions. We offer multiple forms — flakes, minced, chopped, granules, and powder — catering to food manufacturers, seasoning companies, and instant food producers worldwide.",
    origin: "India",
    features: [
      "Multiple forms: flakes, minced, granules, powder",
      "White and red onion varieties",
      "Moisture: < 5%",
      "Strong pungent flavor",
      "No artificial colors or preservatives",
      "Custom particle sizes available",
      "FDA and EU compliant",
    ],
    specifications: {
      "Product": "Dehydrated Onion",
      "Origin": "India (Maharashtra, Gujarat)",
      "Forms": "Flakes / Minced / Granules / Powder",
      "Moisture": "< 5%",
      "Color": "White / Pink",
      "Packaging": "10kg / 20kg cartons",
      "MOQ": "500 kg",
      "Shelf Life": "12 months",
      "Certifications": "FSSAI, ISO 22000, HACCP, FDA",
    },
  },
  {
    slug: "sesame-seeds",
    name: "Sesame Seeds",
    category: "Seeds & Grains",
    categorySlug: "seeds-grains",
    image: "/images/products/sesame-seeds.jpg",
    shortDescription: "Natural and hulled sesame seeds in white, brown, and black varieties for oil extraction and food use.",
    description: "India is one of the world's largest exporters of sesame seeds, and our seeds are sourced from the best-producing regions. We offer natural, hulled, and roasted varieties in white, brown, and black — serving the needs of oil mills, bakeries, and food manufacturers.",
    origin: "India",
    features: [
      "White, brown, and black varieties",
      "Natural and hulled options",
      "High oil content: 48-55%",
      "99%+ purity, sortex-cleaned",
      "Non-GMO verified",
      "Suitable for oil extraction and food use",
      "Competitive FOB/CIF pricing",
    ],
    specifications: {
      "Product": "Sesame Seeds",
      "Origin": "India (Rajasthan, Gujarat, MP)",
      "Varieties": "White / Brown / Black",
      "Oil Content": "48-55%",
      "Moisture": "< 5%",
      "Purity": "99%+",
      "FFA": "< 2%",
      "Packaging": "25kg / 50kg PP bags",
      "MOQ": "1 MT",
      "Shelf Life": "12 months",
      "Certifications": "FSSAI, APEDA, Non-GMO",
    },
  },
  {
    slug: "mustard-oil",
    name: "Mustard Oil",
    category: "Oils",
    categorySlug: "oils",
    image: "/images/products/mustard-oil.jpg",
    shortDescription: "Cold-pressed pure mustard oil with sharp, pungent flavor — a staple in Indian and South Asian cuisine.",
    description: "Our cold-pressed mustard oil is extracted from premium Indian mustard seeds using traditional kachi ghani (cold-press) methods. This preserves the sharp, pungent flavor and nutritional benefits that make mustard oil a preferred cooking medium across South Asia.",
    origin: "India",
    features: [
      "Cold-pressed (Kachi Ghani) extraction",
      "Sharp, pungent characteristic flavor",
      "Rich in omega-3 fatty acids",
      "High smoke point for cooking",
      "No chemical refining process",
      "Available in bulk and consumer packs",
      "AGMARK quality certified",
    ],
    specifications: {
      "Product": "Mustard Oil (Cold-Pressed)",
      "Origin": "India (Rajasthan, UP)",
      "Extraction": "Kachi Ghani (Cold-pressed)",
      "Acid Value": "< 4%",
      "Color": "Golden yellow",
      "Packaging": "15L tins / 200L drums",
      "MOQ": "1000 L",
      "Shelf Life": "12 months",
      "Certifications": "FSSAI, AGMARK",
    },
  },
  {
    slug: "cinnamon-sticks",
    name: "Cinnamon Sticks",
    category: "Whole Spices",
    categorySlug: "whole-spices",
    image: "/images/products/cinnamon.jpg",
    shortDescription: "Premium cassia cinnamon sticks with warm, sweet-spicy aroma, sourced from select Indian plantations.",
    description: "Our cinnamon (cassia) sticks are sourced from the finest bark of Cinnamomum cassia trees grown in the lush regions of Kerala and the Northeastern states of India. Each stick is carefully harvested, dried, and graded to deliver consistent quality and flavor.",
    origin: "India",
    features: [
      "Premium cassia cinnamon bark",
      "Warm, sweet-spicy aroma",
      "Available in split and whole quills",
      "Multiple length grades: 8cm, 15cm, 25cm",
      "High essential oil content",
      "Hand-sorted for quality",
      "Available: sticks and powder",
    ],
    specifications: {
      "Product": "Cinnamon Sticks (Cassia)",
      "Origin": "India (Kerala, NE India)",
      "Grade": "A / B / C",
      "Length": "8cm / 15cm / 25cm",
      "Volatile Oil": "1-3%",
      "Moisture": "< 12%",
      "Packaging": "10kg / 25kg cartons",
      "MOQ": "500 kg",
      "Shelf Life": "24 months",
      "Certifications": "FSSAI, Spice Board",
    },
  },
  {
    slug: "fennel-seeds",
    name: "Fennel Seeds",
    category: "Seeds & Grains",
    categorySlug: "seeds-grains",
    image: "/images/products/fennel.jpg",
    shortDescription: "Bright green fennel seeds with sweet, anise-like flavor from Gujarat — India's fennel capital.",
    description: "Gujarat produces over 80% of India's fennel, and our seeds come from the heart of this region. Known for their bright green color, sweet anise-like flavor, and aromatic essential oils, Indian fennel seeds are in high demand globally for culinary, medicinal, and tea applications.",
    origin: "India",
    features: [
      "Bright green color (Lucknow variety)",
      "Sweet, anise-like flavor",
      "High volatile oil: 1.5-3.5%",
      "Machine-cleaned and sortex-processed",
      "Available: whole seeds and powder",
      "99%+ purity",
      "Suitable for food and pharma use",
    ],
    specifications: {
      "Product": "Fennel Seeds",
      "Origin": "India (Gujarat)",
      "Variety": "Lucknow / Bold",
      "Volatile Oil": "1.5-3.5%",
      "Moisture": "< 10%",
      "Purity": "99%+",
      "Color": "Bright green",
      "Packaging": "25kg / 50kg PP bags",
      "MOQ": "1 MT",
      "Shelf Life": "18 months",
      "Certifications": "FSSAI, APEDA",
    },
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  if (categorySlug === "all") return products;
  return products.filter((p) => p.categorySlug === categorySlug);
}
